### ISSUE TITLE
feat: beta branch for 1.14 RC

### ISSUE THREAD

**Issue by JigSawFr** [astubenbord/paperless-mobile#148]
Think that we need to be prepared for next version: https://github.com/paperless-ngx/paperless-ngx/releases/tag/v1.14.0-beta.rc1

Release scheduled in max 5days on their side.

Multi User support ! ♥️

## Tasks
- [x] Add models
- [ ] Adapt API for v3 (implement user and groups API)
- [ ] Add permissions to documents
- [ ] Add user namespaces for multi-user support
- [ ] Add permission checks to buttons
- [ ] Handle new permission errors

**Comment by astubenbord** [comment]
Great, finally!

I've already looked through the PR and I'm looking forward to testing the permission handling in action. I've seen some of the webclient designs and from what I've seen so far, I'll have to think about how this could be implemented on mobile devices. Also, this will require quite a lot of planning in order to ensure backwards compatibility with older versions, which will inevitably also require some architectural changes. While I'd really like to implement this, my spare time is currently unfortunately very limited, so don't expect this feature to be implemented soon. Also, I'm currently still busy with the bulk edits, which I'd like to finish but I don't quite find the time.

**Comment by astubenbord** [comment]
I've started re-implementing user/account management and also account switching and multi-user-support. Works well so far, but I think since the next release will be a bigger update (bulk edits, reworked form fields, multi user support) I will probably release it as an open beta in google play in the next weeks.
